# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20171108_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
