# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20171108_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='college',
            field=models.CharField(default='iitg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='room_no',
            field=models.CharField(default='126', max_length=255),
            preserve_default=False,
        ),
    ]
