# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20171109_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='email',
            field=models.EmailField(default='a@iitg.in', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
