# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_teachingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingdetails',
            name='semester',
            field=models.CharField(choices=[(1, 'Odd Semester'), (2, 'Even Semester')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
