# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_teachingdetails_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingdetails',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
