# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('details', '0015_auto_20171109_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.CharField(max_length=255)),
                ('pi', models.CharField(max_length=255)),
                ('co_pi', models.CharField(max_length=255)),
                ('funding_agency', models.CharField(max_length=255)),
                ('start_year', models.CharField(max_length=255)),
                ('end_year', models.CharField(max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
