# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('details', '0019_profiledetails_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_status', models.CharField(choices=[('Continuing', 'Continuing'), ('Completed', 'completed')], max_length=255)),
                ('degree', models.CharField(choices=[('B-Tech', 'B-Tech'), ('M-Tech', 'M-Tech'), ('PhD', 'PhD')], max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('thesis_title', models.CharField(max_length=255)),
                ('supervisor', models.CharField(max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
