# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0021_auto_20171117_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
