# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0022_profiledetails_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
