# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0026_notificationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdetails',
            name='type',
            field=models.IntegerField(blank=True),
        ),
    ]
