# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0027_auto_20171118_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdetails',
            name='arg1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
