# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0028_notificationdetails_arg1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognitiondetails',
            name='heading',
        ),
    ]
