# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0029_remove_recognitiondetails_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdetails',
            name='arg2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
