# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0031_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='profile_page',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
